### ISSUE TITLE
Refs

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#102]
Refs provide updateable, shareable values :
```
isRef( x ) -> Bool
lock( x:Ref<T> ), might be deferred to v0.2
r! -> T, where r:Ref<T> ... contRef
r! <-- T, where r:Ref<T>, updates the value of ref r ... setContRef
newVarRef( x ) -> Ref<T>, where x:T; might be deferred to v0.2
newValRef( x ) -> Ref<T>, where x:T; might be deferred to v0.2
newConstRef( x ) -> Ref<T>, where x:T; should be deferred to v0.2
newRef{mut=(#var|#val|#const)}( x ) -> Ref<T>, where x:T and selector mut defaults to #val; optargs might be deferred to v0.2
```

### Tasks

* [x] Create branch `v0.1/102_refs`
* [x] Implement `newVarRef` in C#
* [x] Implement `sealObject` in C#
* [ ] Implement `isRef` in C#
* [ ] Implement `itemRef` in C#
* [ ] Implement `setItemRef` in C#
* [ ] Add some of the above to `syscalls.py`
* [ ] Implement the `!` syntax (tightly binding) as a shorthand for `contRef`
* [ ] Refactor `syscalls.py` into a JSON file to support properties
* [ ] Implement `updaterOf` on top of properties
* [ ] Implement `<--` as syntactic sugar for `updaterOf`
* [ ] Add `setContRef` as the updater of `contRef`
* [ ] Create and merge pull request

### Example
```
val x := 1
val y := Ref(2)
println( x + y! )
### prints 3
y! <-- 99
println( x + y! )
### prints 100
```
