### ISSUE TITLE
Visual Code syntax highlighting for Nutmeg

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#13]
**Statement**
As a coder, when I edit a *.nutmeg file in Visual Code, the contents of the file are syntax highlighted.

**Background**
This is a first cut at doing a Nutmeg extension for Visual Studio. Syntax highlighting is the biggest bang for buck and gives us a modern editor for working with Nutmeg files. This very first version only needs to cover the basic constructs.

**Tasks**
* [x] Create repo for this VS extension.
* [ ] Implement the extension.
* [ ] Build the *.vsix file for distribution.

**Acceptance Criteria**
* [ ] Highlights end-of-line comments. Long comments are not required yet.
* [ ] Highlights strings with single and double quotes, including escape characters. Interpolation not required yet.
* [ ] Highlights decimal integers and decimal floating point numbers. Should allow for underscores in numbers. But other radices are not required yet.
* [ ]  Identifiers are highlighted.
* [ ] Keywords `def` .... `end` | `enddef` are highlighted
* [ ] Keywords `if`, `then`, `else`, `elseif`, `endif`, `end` are highlighted
* [ ] Comments, literals, identifiers and keywords have distinct styling.
