### ISSUE TITLE
Short circuit conditionals

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#76]
**Statement**
Add `and`  and `or`  to the language.

**Tasks**

* [x] Create branch v0.1/76_short_circuit_conditionals
* [x] Add to the codetrees for the compiler
* [x] Add `and` and `or` to the tokeniser
* [x] Add to the parser
* [x] Add to the codetrees for the runner
* [x] Create pull request
* [x] Check CircleCI results
* [ ] Merge pull request
