### ISSUE TITLE
Syntax errors report tokens correctly

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#78]
**Statement**
When the parser finds a problem, it should report any tokens involved without excessive and irrelevant 'decorations' but in a simple and intuitive way.

**Tasks**

* [x] Create branch v0.1/78_nice_tokens
* [x] Modify the way tokens are printed by the parse so that they show the original text
* [x] Push branch and check CircleCI status
* [x] Create and merge pull request
