### ISSUE TITLE
Modify the fields of the if-codelet

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#9]
Modify the fields of the if-codelet to fit the wiki description of TEST/THEN/ELSE.

* `test` for the predicate (ancedent)
* `then` for the then-part (consequent)
* `else` for the else-part (alternative consequent)

## Tasks
* [x] Create branch: `v0.1/9_amend_if`
* [x] Ensure wiki pages are consistent with the new format: they were already, see [1](/Spicery/Nutmeg/wiki/CodeTrees-in-JSON) and [2](/Spicery/Nutmeg/wiki/Codetree-Examples:-If).
* [x] Fix running examples in simple.bundle file.
* [x] Amend the codetree.py file.
* [x] Add unit tests for the new format.
