### ISSUE TITLE
'while' loop modifier

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#94]
Add  the while loop-modifier so that you can write:
```
for i in L while f(i) do ... endfor
```

# Tasks

* [x] Add new codetree types to the wiki
* [x] Document the new syntax in the EBNF
* [ ] Post a screenshot of is_prime to the Slack channel
