### ISSUE TITLE
Lambda expressions

### ISSUE THREAD

**Issue by sfkleach** [Spicery/Nutmeg#96]
**Syntax**
```
fn ARGS =>> endfn
```

**Tasks**
* [x] Create branch v0.1/96_lambdas
* [ ] Amend the syntax highlighter
* [ ] Amend the grammar docs
* [ ] Update tokenizer.py
* [ ] Update parser.py
* [ ] Update codetree.py
* [ ] Update resolver.py
* [ ] Update Codelet.cs with the new type
